pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'Maven') {
                    sh "mvn install -Dmaven.test.skip=true -pl employee-service"
                    sh "docker build -t employee-service . -f employee-service/Dockerfile"
                }
            }
            post {
                success {
                    archiveArtifacts 'employee-service/target/*.jar'
                }
            }
        }
        stage('Deploy') {
            steps {
                withMaven(maven: 'Maven') {
                    sh "docker rm -f employee-service"
                    sh "docker run -d --name employee-service -p 8080:8080 --network spring-microservices-testing_default employee-service"
                }
            }
        }
    }
}
