pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh "mvn clean install -Dmaven.test.skip=true -pl department-service"
                sh "docker build -t department-service . -f department-service/Dockerfile"
            }
            post {
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh "docker run --name department-service -p 8080:8080 --network spring-microservices-testing_default department-service"
            }
        }
    }
}
