pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'Maven') {
                    sh "mvn install -Dmaven.test.skip=true -pl department-service"
                    sh "docker build -t department-service . -f department-service/Dockerfile"
                }
            }
            post {
                success {
                    archiveArtifacts 'department-service/target/*.jar'
                }
            }
        }
        stage('Deploy') {
            steps {
                withMaven(maven: 'Maven') {
                    sh "docker run --name department-service -p 8080:8080 --network spring-microservices-testing_default department-service"
                }
            }
        }
    }
}
